spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

    show-sql: true

#security:
#  user:
#    name: admin
#    password: admin123
#    roles: ADMIN

flyway:
  baseline-on-migrate: true

server:
  port: 8090

logging:
  level:
    org.springframework: DEBUG
